### ISSUE TITLE
Gateway crashes with unknown packet type

### ISSUE THREAD

**Issue by kennybytes** [scel-hawaii/data-gateway#3]
The current gateway script crashes when it doesn't recognize a packet. Ideally, it shouldn't crash and should try to continue collecting data. If there is a partial or corrupted packet, the script will crash.

Incident:

```
time_received: 2016-10-27 16:49:09.434853
uptime_ms: 31440000
batt_mv: 3750
node_addr: 777
schema: 0
time_received: 2016-10-27 16:49:10.761077
uptime_ms: 147193
Traceback (most recent call last):
  File "packet_tester.py", line 24, in <module>
    xbg.begin_test()
  File "/home/control_tower/data-gateway/Gateway_v2/xbee_gateway.py", line 51, in begin_test
    callback(data, timestamp)
  File "/home/control_tower/data-gateway/Gateway_v2/decoder.py", line 40, in decode_data
    dataDict = self.sort_packet(data, timestamp)
  File "/home/control_tower/data-gateway/Gateway_v2/decoder.py", line 110, in sort_packet
    unpacked_data = struct.unpack(fmt,data)
struct.error: unpack requires a string argument of length 20
```

**Comment by byerst** [comment]
The gateway should no longer crash when receiving an unexpected packet and should continue collecting data following commit b50db87cab8539b349836fb56167dd080f706f46
